import React from 'react';
import { Footer } from '@/components/static/Footer';
import './globals.css';
import { Navbar } from '@/components/static/Navbar';

export const metadata = {
    title: 'Houston ARTCC',
    description: 'Generated by create next app',
};

interface LayoutProps {
    children: React.ReactNode;
}

const Root = ({ children }: LayoutProps) => (
    <html lang="en">
        <body>
            <Navbar />
            {children}
            <Footer />
        </body>
    </html>
);

export default Root;
