import React, { type PropsWithChildren } from 'react';
import { NextAuthProvider } from '@/components/static/NextAuthProvider';
import { Footer } from '@/components/static/Footer';
import { Navbar } from '@/components/static/Navbar';
import './fonts.css';
import './globals.css';

export const metadata = {
    title: 'Houston ARTCC',
    description: 'Generated by create next app',
};

const Root = ({ children }: PropsWithChildren) => (
    <html lang="en">
        <body>
            <NextAuthProvider>
                <Navbar />
                {children}
                <Footer />
            </NextAuthProvider>
        </body>
    </html>
);

export default Root;
