# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🔨 Build React App

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> .env
        echo REACT_APP_VATSIM_CONNECT_CLIENT_ID=${{ secrets.REACT_APP_VATSIM_CONNECT_CLIENT_ID }} >> .env
        echo REACT_APP_VATSIM_CONNECT_REDIRECT_URI=${{ secrets.REACT_APP_VATSIM_CONNECT_REDIRECT_URI }} >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
